### ISSUE TITLE
Plugin version

### ISSUE THREAD

**Issue by Bultako** [AMIGA-IAA/AstroTaverna-AA-article#8]
Check before sendign the paper, that last version of plugin is correct in the text.

**Comment by julian-garrido** [comment]
Now, it is 1.08 but I will do another release to include the latest changes. should I wait until the aladin macro issue is finally solved?

**Comment by Bultako** [comment]
Ok
if last devels with Aladin macro are finished and released before sending the paper, we will change the version number in the paper. I think this is more a reminder than an issue :)
